name: Deploy to Server

on:
  push:
    branches:
      - main  # Spustí se jen když pushneš do main větve

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Připojení přes SSH a update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/Cordel
            git fetch origin main
            git reset --hard origin/main
            npm install
            pm2 restart cordel